apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - .infra\k8s\*.yaml
build:
  local:
    push: false
  artifacts:
    - image: matfij/nw-auth
      context: apps/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.ts'
    - image: matfij/nw-items
      context: apps/items
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.ts'
    - image: matfij/nw-client
      context: apps/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
