name: deploy-manifest

# on:
#   push:
#     branches:
#       - 'main'
#     paths:
#       - '.infra/**'

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save nw-outlet
      - run: kubectl apply -f .infra/k8s -f .infra/k8s-prod
          