name: deploy-auth

# on:
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'apps/auth/**'

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd apps/auth && docker build -t matfij/nw-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push matfij/nw-auth
          