name: test-orders

on: 
  pull_request:
    paths:
      - 'apps/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd apps/orders && npm install && npm run test:ci
